name: tgbot_dart
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  web: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.0
  telebot: ^1.0.3